# Generated by Django 5.2.1 on 2025-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_description_product_feature1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spec1',
            new_name='spec_value1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec2',
            new_name='spec_value2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec3',
            new_name='spec_value3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec4',
            new_name='spec_value4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec5',
            new_name='spec_value5',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec6',
            new_name='spec_value6',
        ),
        migrations.AddField(
            model_name='product',
            name='spec_label1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_label2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_label3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_label4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_label5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_label6',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
