# Generated by Django 5.2.1 on 2025-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_village', models.CharField(max_length=100)),
                ('address_union', models.CharField(max_length=100)),
                ('address_post', models.CharField(max_length=100)),
                ('address_thana', models.CharField(max_length=100)),
                ('address_district', models.CharField(max_length=100)),
                ('delivery_village', models.CharField(max_length=100)),
                ('delivery_union', models.CharField(max_length=100)),
                ('delivery_post', models.CharField(max_length=100)),
                ('delivery_thana', models.CharField(max_length=100)),
                ('delivery_district', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
