# Generated by Django 5.2.1 on 2025-06-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_post',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_thana',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_union',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_village',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_post',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_thana',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_union',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_village',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
